FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD swagger-demo.jar /opt/swagger-demo/
EXPOSE 8080
WORKDIR /opt/swagger-demo/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "swagger-demo.jar"]
